<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CalculateurPokemon</RootNamespace>
    <AssemblyName>CalculateurPokemon</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pokemon.Battle\PokemonBattle.csproj" />
    <ProjectReference Include="..\Pokemon.Core\PokemonCore.csproj" />
    <ProjectReference Include="..\Pokemon.Data\PokemonData.csproj" />
  </ItemGroup>

</Project>
